import type { Metadata } from 'next'
import '@mantine/core/styles.css'
import '@/app/globals.css'
import { ColorSchemeScript, MantineProvider, mantineHtmlProps, MantineColorsTuple, createTheme } from '@mantine/core'
import { Header } from '@/app/ui/header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const paleIndigo: MantineColorsTuple = [
  '#eff2ff',
  '#dfe2f2',
  '#bdc2de',
  '#99a0ca',
  '#7a84b9',
  '#6672af',
  '#5c69ac',
  '#4c5897',
  '#424e88',
  '#36437a',
]

const theme = createTheme({
  colors: {
    'pale-indigo': paleIndigo,
  },
  primaryColor: 'pale-indigo',
})

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      {...mantineHtmlProps}
    >
      <head>
        <ColorSchemeScript defaultColorScheme="dark" />
      </head>
      <body>
        <MantineProvider
          theme={theme}
          defaultColorScheme="dark"
        >
          <Header />
          {children}
        </MantineProvider>
      </body>
    </html>
  )
}
